### ISSUE TITLE
Installation problem on Azure Cloud shell with Python 3.5.2

### ISSUE THREAD

**Issue by jkuruzovich** [CarmeLabs/carme#54]
Hey guys.  I'm running into a Python error that seems strange when installing on the AZURE Cloud shell.  

Python 3.5.2 

```
(carme-env) jason@Azure:~/carme$ pip3 install -e .
Obtaining file:///home/jason/carme
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/jason/carme/setup.py", line 9, in <module>
        from src import __version__
      File "/home/jason/carme/src/__init__.py", line 1, in <module>
        from .cli import __version__
      File "/home/jason/carme/src/cli/__init__.py", line 2, in <module>
        from .cli import *
      File "/home/jason/carme/src/cli/cli.py", line 2, in <module>
        from .commands import new, save, package, git, lab, build, notebook, cmd, start, stop, cleanup, convert
      File "/home/jason/carme/src/cli/commands/__init__.py", line 1, in <module>
        from .new import *
      File "/home/jason/carme/src/cli/commands/new.py", line 8, in <module>
        from .package import _install_package
      File "/home/jason/carme/src/cli/commands/package.py", line 8, in <module>
        from ...modules.packager import Packager
      File "/home/jason/carme/src/modules/packager.py", line 29
        project_root: str = None
                    ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/jason/carme/

```

Line 29 is: 

```
    project_root: str = None
    zip_path: str = None
    unzipped_path: str = None
    download_URL: str = None
```

I'm guessing this is something that is an oop syntax that has changed.

**Comment by jkuruzovich** [comment]
It seemed that changing the variable specification worked ok.
